### ISSUE TITLE
Alternative for soldering

### ISSUE THREAD

**Issue by Vrolijk** [klockcykel/godiode#1] opened 2022-02-15 21:33 UTC
When i opened the TP-link and saw the size of the pcb i got worried and used a different setup using a PLC fiber splitter. 
See https://github.com/Vrolijk/OSDD/blob/main/datadiode_hardware_setups.md for the setup.
Have you also considered this setup? 

I did noticed double packets in wireshark when i send data on the TX side because of the TX-RX loop. 
I wondered if you also have this on your setup when you solder the connection?

Regards,
René

**Comment by klockcykel** [comment] 2022-02-16 13:20
Nice writeup :) Yes, the components on the PCB are pretty small but I've soldered a bunch of them using a regular soldering iron without a microscope and yet to see any failures. The area and components where the soldering takes place is far away from any IC's and not very sensitive.

I considered a PLC splitter as well but one of the goals of this project was to be able to buy everything anonymously (cash over the counter) and fiber splitters are not readily available at computer stores (at least not in Sweden).

Yes you would see duplicate of the sent packets when the interface is in promiscuous mode but otherwise dropped by the kernel. I believe the performance impact should be negligible though.

**Comment by Vrolijk** [comment] 2022-02-16 19:19
Thanks!  Respect for the fine soldering. 👍 

I got the MPCP messages because i used a single mode fiber splitter on a multi mode media converter. Switching to the TP-Link MC210CS solved the issue.

Your message about the duplicate packets helped to solve this! 🥇 .

**Closed as completed** 2022-02-16 19:18 UTC
